/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : AlertId,
  'alertType' : AlertType,
  'resourceId' : [] | [string],
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'employeeId' : [] | [EmployeeId],
  'message' : string,
  'severity' : AlertSeverity,
  'readAt' : [] | [Timestamp],
  'readBy' : [] | [UserId],
  'companyId' : CompanyId,
}
export type AlertId = bigint;
export type AlertSeverity = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type AlertType = { 'DocumentExpiring' : null } |
  { 'PayrollPending' : null } |
  { 'VisaExpiring' : null } |
  { 'ComplianceRisk' : null };
export type ApiError = { 'forbidden' : string } |
  { 'invalidInput' : string } |
  { 'notFound' : string } |
  { 'limitExceeded' : string } |
  { 'unauthorized' : string };
export interface AttendanceLog {
  'id' : AttendanceLogId,
  'createdAt' : Timestamp,
  'checkInTime' : Timestamp,
  'employeeId' : EmployeeId,
  'selfieBlob' : [] | [ExternalBlob],
  'consentGiven' : boolean,
  'checkInLocation' : [] | [GeoLocation],
  'checkOutTime' : [] | [Timestamp],
  'checkOutLocation' : [] | [GeoLocation],
  'workHours' : [] | [number],
  'companyId' : CompanyId,
}
export type AttendanceLogId = bigint;
export type AuditActionType = { 'DocumentDeleted' : null } |
  { 'WPSExported' : null } |
  { 'DocumentDownloaded' : null } |
  { 'DocumentUploaded' : null } |
  { 'EmployeeAdded' : null } |
  { 'SalaryChanged' : null } |
  { 'AlertThresholdChanged' : null } |
  { 'EmployeeDeleted' : null } |
  { 'UserLogin' : null } |
  { 'RoleChanged' : null } |
  { 'CompanyProfileUpdated' : null } |
  { 'PayrollApproved' : null };
export interface AuditLog {
  'id' : AuditLogId,
  'status' : AuditStatus,
  'oldValue' : [] | [string],
  'userId' : UserId,
  'createdAt' : Timestamp,
  'newValue' : [] | [string],
  'actionType' : AuditActionType,
  'affectedResourceId' : string,
  'affectedResourceName' : string,
  'affectedResourceType' : string,
  'companyId' : CompanyId,
}
export type AuditLogId = bigint;
export type AuditStatus = { 'Success' : null } |
  { 'Failure' : null };
export interface CheckInInput {
  'employeeId' : EmployeeId,
  'selfieBlob' : [] | [ExternalBlob],
  'consentGiven' : boolean,
  'checkInLocation' : [] | [GeoLocation],
}
export interface CheckOutInput {
  'logId' : AttendanceLogId,
  'checkOutLocation' : [] | [GeoLocation],
}
export interface Company {
  'id' : CompanyId,
  'trialEndDate' : [] | [Timestamp],
  'country' : string,
  'alertThresholdDays' : Array<bigint>,
  'name' : string,
  'createdAt' : Timestamp,
  'subscriptionTier' : SubscriptionTier,
  'registrationNumber' : string,
  'vatNumber' : string,
  'address' : string,
  'billingEmail' : string,
  'phone' : string,
}
export type CompanyId = bigint;
export interface CompanyInput {
  'country' : string,
  'name' : string,
  'registrationNumber' : string,
  'vatNumber' : string,
  'address' : string,
  'billingEmail' : string,
  'phone' : string,
}
export interface ComplianceRiskScore {
  'riskFactors' : Array<RiskFactor>,
  'score' : bigint,
  'currency' : string,
  'riskLevel' : { 'Low' : null } |
    { 'High' : null } |
    { 'Medium' : null } |
    { 'Critical' : null },
  'penaltyExposure' : bigint,
}
export interface CreateNotificationEntry {
  'notificationType' : { 'Salary' : null } |
    { 'VisaAlert' : null } |
    { 'PayrollApproval' : null },
  'employeeId' : [] | [EmployeeId],
  'message' : string,
}
export type DocumentId = bigint;
export interface DocumentInput {
  'documentType' : DocumentType,
  'expiryDate' : [] | [Timestamp],
  'blob' : ExternalBlob,
  'mimeType' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'employeeId' : EmployeeId,
}
export type DocumentType = { 'ID' : null } |
  { 'Contract' : null } |
  { 'Insurance' : null } |
  { 'PassportCopy' : null } |
  { 'Visa' : null } |
  { 'BankDocuments' : null } |
  { 'Medical' : null };
export interface Employee {
  'id' : EmployeeId,
  'status' : EmployeeStatus,
  'employeeCode' : string,
  'iban' : string,
  'createdAt' : Timestamp,
  'joiningDate' : Timestamp,
  'fullName' : string,
  'nationality' : string,
  'visaNumber' : string,
  'bankName' : string,
  'contractEndDate' : [] | [Timestamp],
  'emiratesId' : string,
  'updatedAt' : Timestamp,
  'jobTitle' : string,
  'passportNumber' : string,
  'department' : string,
  'contractStartDate' : Timestamp,
  'basicSalary' : bigint,
  'workLocation' : WorkLocation,
  'companyId' : CompanyId,
}
export interface EmployeeDocument {
  'id' : DocumentId,
  'documentType' : DocumentType,
  'expiryDate' : [] | [Timestamp],
  'blob' : ExternalBlob,
  'createdAt' : Timestamp,
  'mimeType' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'employeeId' : EmployeeId,
  'uploadedBy' : UserId,
  'companyId' : CompanyId,
}
export type EmployeeId = bigint;
export interface EmployeeImportRow {
  'employeeCode' : string,
  'fullName' : string,
  'nationality' : string,
  'jobTitle' : string,
  'department' : string,
  'basicSalary' : bigint,
  'workLocation' : string,
}
export interface EmployeeInput {
  'employeeCode' : string,
  'iban' : string,
  'joiningDate' : Timestamp,
  'fullName' : string,
  'nationality' : string,
  'visaNumber' : string,
  'bankName' : string,
  'contractEndDate' : [] | [Timestamp],
  'emiratesId' : string,
  'jobTitle' : string,
  'passportNumber' : string,
  'department' : string,
  'contractStartDate' : Timestamp,
  'basicSalary' : bigint,
  'workLocation' : WorkLocation,
}
export type EmployeeStatus = { 'Active' : null } |
  { 'Separated' : null } |
  { 'OnLeave' : null };
export type ExpiryStatus = { 'Valid' : null } |
  { 'ExpiringSoon' : bigint } |
  { 'Expired' : null };
export type ExternalBlob = Uint8Array;
export interface GeoLocation { 'latitude' : number, 'longitude' : number }
export interface ImportError { 'row' : bigint, 'reason' : string }
export interface ImportResult {
  'imported' : bigint,
  'errors' : Array<ImportError>,
}
export interface NotificationLog {
  'id' : bigint,
  'status' : { 'Failed' : null } |
    { 'Sent' : null } |
    { 'Pending' : null },
  'notificationType' : { 'Salary' : null } |
    { 'VisaAlert' : null } |
    { 'PayrollApproval' : null },
  'createdAt' : Timestamp,
  'employeeId' : [] | [EmployeeId],
  'message' : string,
  'companyId' : CompanyId,
}
export interface OnboardingProgress {
  'completedAt' : [] | [Timestamp],
  'currentStep' : bigint,
  'stepsCompleted' : Array<boolean>,
  'companyId' : CompanyId,
}
export interface PayrollItem {
  'id' : PayrollItemId,
  'createdAt' : Timestamp,
  'overtime' : bigint,
  'deductions' : bigint,
  'netSalary' : bigint,
  'payrollRunId' : PayrollRunId,
  'updatedAt' : Timestamp,
  'transportAllowance' : bigint,
  'employeeId' : EmployeeId,
  'leaveDeduction' : bigint,
  'basicSalary' : bigint,
  'advanceSalary' : bigint,
  'housingAllowance' : bigint,
}
export type PayrollItemId = bigint;
export interface PayrollItemInput {
  'overtime' : bigint,
  'deductions' : bigint,
  'transportAllowance' : bigint,
  'employeeId' : EmployeeId,
  'leaveDeduction' : bigint,
  'basicSalary' : bigint,
  'advanceSalary' : bigint,
  'housingAllowance' : bigint,
}
export interface PayrollRun {
  'id' : PayrollRunId,
  'status' : PayrollStatus,
  'totalNetSalary' : bigint,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'hrApprovedAt' : [] | [Timestamp],
  'hrApprovedBy' : [] | [UserId],
  'payPeriodYear' : bigint,
  'accountantReviewedAt' : [] | [Timestamp],
  'accountantReviewedBy' : [] | [UserId],
  'exportedAt' : [] | [Timestamp],
  'notes' : string,
  'ownerApprovedAt' : [] | [Timestamp],
  'ownerApprovedBy' : [] | [UserId],
  'payPeriodMonth' : bigint,
  'employeeIds' : Array<EmployeeId>,
  'companyId' : CompanyId,
}
export type PayrollRunId = bigint;
export interface PayrollRunInput {
  'payPeriodYear' : bigint,
  'notes' : string,
  'payPeriodMonth' : bigint,
  'employeeIds' : Array<EmployeeId>,
}
export type PayrollStatus = { 'HRApproved' : null } |
  { 'Paid' : null } |
  { 'AccountantReviewed' : null } |
  { 'Draft' : null } |
  { 'OwnerApproved' : null } |
  { 'Exported' : null };
export interface PenaltyBreakdown {
  'count' : bigint,
  'category' : string,
  'amount' : bigint,
}
export interface PenaltyExposure {
  'total' : bigint,
  'breakdown' : Array<PenaltyBreakdown>,
  'currency' : string,
}
export interface ROIMetrics {
  'payrollTotalAmount' : bigint,
  'timeSavedHours' : number,
  'complianceScoreImprovement' : number,
  'payrollProcessedCount' : bigint,
  'currency' : string,
  'estimatedPenaltiesAvoided' : bigint,
}
export type Result = { 'ok' : Array<string> } |
  { 'err' : ApiError };
export type Result_1 = { 'ok' : PayrollItem } |
  { 'err' : ApiError };
export type Result_10 = { 'ok' : boolean } |
  { 'err' : ApiError };
export type Result_11 = { 'ok' : Array<WpsExport> } |
  { 'err' : ApiError };
export type Result_12 = {
    'ok' : Array<{ 'status' : ExpiryStatus, 'record' : VisaRecord }>
  } |
  { 'err' : ApiError };
export type Result_13 = { 'ok' : Array<VisaRecord> } |
  { 'err' : ApiError };
export type Result_14 = { 'ok' : Array<User> } |
  { 'err' : ApiError };
export type Result_15 = { 'ok' : Array<Alert> } |
  { 'err' : ApiError };
export type Result_16 = { 'ok' : Array<PayrollRun> } |
  { 'err' : ApiError };
export type Result_17 = { 'ok' : Array<PayrollItem> } |
  { 'err' : ApiError };
export type Result_18 = { 'ok' : Array<NotificationLog> } |
  { 'err' : ApiError };
export type Result_19 = { 'ok' : Array<Employee> } |
  { 'err' : ApiError };
export type Result_2 = { 'ok' : EmployeeDocument } |
  { 'err' : ApiError };
export type Result_20 = { 'ok' : Array<EmployeeDocument> } |
  { 'err' : ApiError };
export type Result_21 = { 'ok' : Array<AuditLog> } |
  { 'err' : ApiError };
export type Result_22 = { 'ok' : Array<AttendanceLog> } |
  { 'err' : ApiError };
export type Result_23 = { 'ok' : WhatsAppSettings } |
  { 'err' : ApiError };
export type Result_24 = { 'ok' : ROIMetrics } |
  { 'err' : ApiError };
export type Result_25 = { 'ok' : PenaltyExposure } |
  { 'err' : ApiError };
export type Result_26 = { 'ok' : PayrollRun } |
  { 'err' : ApiError };
export type Result_27 = { 'ok' : ComplianceRiskScore } |
  { 'err' : ApiError };
export type Result_28 = {
    'ok' : {
      'totalEmployees' : bigint,
      'expiredVisaCount' : bigint,
      'unreadAlertCount' : bigint,
      'complianceScore' : bigint,
      'pendingPayrollCount' : bigint,
      'expiringDocumentCount' : bigint,
    }
  } |
  { 'err' : ApiError };
export type Result_29 = { 'ok' : [] | [AttendanceLog] } |
  { 'err' : ApiError };
export type Result_3 = { 'ok' : Subscription } |
  { 'err' : ApiError };
export type Result_30 = {
    'ok' : { 'fileContent' : string, 'export' : WpsExport }
  } |
  { 'err' : ApiError };
export type Result_31 = { 'ok' : NotificationLog } |
  { 'err' : ApiError };
export type Result_32 = { 'ok' : AttendanceLog } |
  { 'err' : ApiError };
export type Result_33 = { 'ok' : ImportResult } |
  { 'err' : ApiError };
export type Result_4 = { 'ok' : null } |
  { 'err' : ApiError };
export type Result_5 = { 'ok' : VisaRecord } |
  { 'err' : ApiError };
export type Result_6 = { 'ok' : User } |
  { 'err' : ApiError };
export type Result_7 = { 'ok' : OnboardingProgress } |
  { 'err' : ApiError };
export type Result_8 = { 'ok' : Employee } |
  { 'err' : ApiError };
export type Result_9 = { 'ok' : Company } |
  { 'err' : ApiError };
export interface RiskFactor {
  'employeeCount' : bigint,
  'description' : string,
  'severity' : string,
  'factorType' : { 'PayrollDelay' : null } |
    { 'MissingDocument' : null } |
    { 'VisaExpiry' : null } |
    { 'WpsError' : null },
  'estimatedFine' : bigint,
}
export interface Subscription {
  'id' : SubscriptionId,
  'paidStartDate' : [] | [Timestamp],
  'status' : SubscriptionStatus,
  'trialEndDate' : [] | [Timestamp],
  'isTrialActive' : boolean,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
  'employeeLimit' : bigint,
  'trialStartDate' : [] | [Timestamp],
  'renewalDate' : [] | [Timestamp],
  'companyId' : CompanyId,
}
export type SubscriptionId = bigint;
export type SubscriptionStatus = { 'Active' : null } |
  { 'Cancelled' : null } |
  { 'Expired' : null };
export type SubscriptionTier = { 'Starter' : null } |
  { 'Enterprise' : null } |
  { 'Growth' : null } |
  { 'Business' : null };
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'status' : UserStatus,
  'principal' : Principal,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'fullName' : string,
  'email' : string,
  'lastLogin' : [] | [Timestamp],
  'companyId' : CompanyId,
}
export type UserId = bigint;
export interface UserInput {
  'role' : UserRole,
  'fullName' : string,
  'email' : string,
}
export type UserRole = { 'Employee' : null } |
  { 'BranchManager' : null } |
  { 'SuperAdmin' : null } |
  { 'HRManager' : null } |
  { 'CompanyOwner' : null } |
  { 'Accountant' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'Suspended' : null };
export interface VisaRecord {
  'id' : VisaRecordId,
  'expiryDate' : Timestamp,
  'createdAt' : Timestamp,
  'recordType' : VisaRecordType,
  'updatedAt' : Timestamp,
  'employeeId' : EmployeeId,
  'notes' : string,
  'companyId' : CompanyId,
}
export type VisaRecordId = bigint;
export interface VisaRecordInput {
  'expiryDate' : Timestamp,
  'recordType' : VisaRecordType,
  'employeeId' : EmployeeId,
  'notes' : string,
}
export type VisaRecordType = { 'Contract' : null } |
  { 'Insurance' : null } |
  { 'Passport' : null } |
  { 'Visa' : null } |
  { 'LabourCard' : null } |
  { 'MedicalCard' : null };
export interface WhatsAppSettings {
  'payrollApprovalEnabled' : boolean,
  'employeeId' : EmployeeId,
  'salaryEnabled' : boolean,
  'phoneNumber' : string,
  'visaAlertEnabled' : boolean,
}
export type WorkLocation = { 'UAE' : null } |
  { 'Saudi' : null } |
  { 'Oman' : null } |
  { 'Kuwait' : null } |
  { 'Bahrain' : null } |
  { 'Qatar' : null };
export type WpsCountryFormat = { 'OmanMOL' : null } |
  { 'SaudiTemplate' : null } |
  { 'UAESIF' : null } |
  { 'QatarTemplate' : null };
export interface WpsExport {
  'id' : WpsExportId,
  'status' : WpsExportStatus,
  'employeeCount' : bigint,
  'createdAt' : Timestamp,
  'fileName' : string,
  'exportedBy' : UserId,
  'payrollRunId' : PayrollRunId,
  'countryFormat' : WpsCountryFormat,
  'companyId' : CompanyId,
}
export type WpsExportId = bigint;
export interface WpsExportInput {
  'payrollRunId' : PayrollRunId,
  'countryFormat' : WpsCountryFormat,
}
export type WpsExportStatus = { 'Failed' : null } |
  { 'Generated' : null } |
  { 'Submitted' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addEmployee' : ActorMethod<[EmployeeInput], Result_8>,
  'addVisaRecord' : ActorMethod<[VisaRecordInput], Result_5>,
  'approvePayrollRun' : ActorMethod<[PayrollRunId, PayrollStatus], Result_26>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'bulkImportEmployees' : ActorMethod<[Array<EmployeeImportRow>], Result_33>,
  'checkIn' : ActorMethod<[CheckInInput], Result_32>,
  'checkOut' : ActorMethod<[CheckOutInput], Result_32>,
  'createNotificationLog' : ActorMethod<[CreateNotificationEntry], Result_31>,
  'createPayrollRun' : ActorMethod<[PayrollRunInput], Result_26>,
  'deactivateUser' : ActorMethod<[UserId], Result_6>,
  'deleteDocument' : ActorMethod<[DocumentId], Result_10>,
  'generateWpsExport' : ActorMethod<[WpsExportInput], Result_30>,
  'getActiveCheckIn' : ActorMethod<[EmployeeId], Result_29>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCompanyStats' : ActorMethod<[], Result_28>,
  'getComplianceRiskScore' : ActorMethod<[], Result_27>,
  'getDocument' : ActorMethod<[DocumentId], Result_2>,
  'getEmployee' : ActorMethod<[EmployeeId], Result_8>,
  'getExpiringRecords' : ActorMethod<[bigint], Result_13>,
  'getMyCompany' : ActorMethod<[], Result_9>,
  'getMyProfile' : ActorMethod<[], Result_6>,
  'getOnboardingProgress' : ActorMethod<[], Result_7>,
  'getPayrollRun' : ActorMethod<[PayrollRunId], Result_26>,
  'getPenaltyExposure' : ActorMethod<[], Result_25>,
  'getROIMetrics' : ActorMethod<[], Result_24>,
  'getSubscription' : ActorMethod<[], Result_3>,
  'getWhatsAppSettings' : ActorMethod<[EmployeeId], Result_23>,
  'initSeedData' : ActorMethod<[], boolean>,
  'inviteUser' : ActorMethod<[UserInput], Result_6>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSeedDataLoaded' : ActorMethod<[], boolean>,
  'listAlerts' : ActorMethod<[], Result_15>,
  'listAllAttendanceLogs' : ActorMethod<[], Result_22>,
  'listAllDocuments' : ActorMethod<[], Result_20>,
  'listAllVisaRecords' : ActorMethod<[], Result_13>,
  'listAttendanceByMonth' : ActorMethod<[bigint, bigint], Result_22>,
  'listAttendanceLogs' : ActorMethod<[EmployeeId], Result_22>,
  'listAuditLogs' : ActorMethod<[], Result_21>,
  'listAuditLogsByAction' : ActorMethod<[AuditActionType], Result_21>,
  'listAuditLogsByDateRange' : ActorMethod<[Timestamp, Timestamp], Result_21>,
  'listAuditLogsByUser' : ActorMethod<[UserId], Result_21>,
  'listDocuments' : ActorMethod<[EmployeeId], Result_20>,
  'listEmployees' : ActorMethod<[], Result_19>,
  'listNotificationLogs' : ActorMethod<[bigint], Result_18>,
  'listPayrollItems' : ActorMethod<[PayrollRunId], Result_17>,
  'listPayrollRuns' : ActorMethod<[], Result_16>,
  'listUnreadAlerts' : ActorMethod<[], Result_15>,
  'listUsers' : ActorMethod<[], Result_14>,
  'listVisaRecords' : ActorMethod<[EmployeeId], Result_13>,
  'listVisaRecordsWithStatus' : ActorMethod<[], Result_12>,
  'listWpsExports' : ActorMethod<[], Result_11>,
  'logDocumentDownload' : ActorMethod<[DocumentId], Result_10>,
  'markAlertRead' : ActorMethod<[AlertId], Result_10>,
  'markAllAlertsRead' : ActorMethod<[], Result_10>,
  'recordMyLogin' : ActorMethod<[], Result_6>,
  'registerCompany' : ActorMethod<[CompanyInput], Result_9>,
  'registerUser' : ActorMethod<[CompanyId, UserInput], Result_6>,
  'removeEmployee' : ActorMethod<[EmployeeId], Result_10>,
  'removeVisaRecord' : ActorMethod<[VisaRecordId], Result_10>,
  'updateAlertThresholds' : ActorMethod<[Array<bigint>], Result_9>,
  'updateCompanyProfile' : ActorMethod<[CompanyInput], Result_9>,
  'updateEmployee' : ActorMethod<[EmployeeId, EmployeeInput], Result_8>,
  'updateOnboardingProgress' : ActorMethod<[bigint], Result_7>,
  'updateUserRole' : ActorMethod<[UserId, UserRole], Result_6>,
  'updateVisaRecord' : ActorMethod<[VisaRecordId, VisaRecordInput], Result_5>,
  'updateWhatsAppSettings' : ActorMethod<[WhatsAppSettings], Result_4>,
  'upgradeSubscription' : ActorMethod<[SubscriptionTier], Result_3>,
  'uploadDocument' : ActorMethod<[DocumentInput], Result_2>,
  'upsertPayrollItem' : ActorMethod<[PayrollRunId, PayrollItemInput], Result_1>,
  'validateWpsData' : ActorMethod<[PayrollRunId], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];