/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Int;
export const WorkLocation = IDL.Variant({
  'UAE' : IDL.Null,
  'Saudi' : IDL.Null,
  'Oman' : IDL.Null,
  'Kuwait' : IDL.Null,
  'Bahrain' : IDL.Null,
  'Qatar' : IDL.Null,
});
export const EmployeeInput = IDL.Record({
  'employeeCode' : IDL.Text,
  'iban' : IDL.Text,
  'joiningDate' : Timestamp,
  'fullName' : IDL.Text,
  'nationality' : IDL.Text,
  'visaNumber' : IDL.Text,
  'bankName' : IDL.Text,
  'contractEndDate' : IDL.Opt(Timestamp),
  'emiratesId' : IDL.Text,
  'jobTitle' : IDL.Text,
  'passportNumber' : IDL.Text,
  'department' : IDL.Text,
  'contractStartDate' : Timestamp,
  'basicSalary' : IDL.Nat,
  'workLocation' : WorkLocation,
});
export const EmployeeId = IDL.Nat;
export const EmployeeStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Separated' : IDL.Null,
  'OnLeave' : IDL.Null,
});
export const CompanyId = IDL.Nat;
export const Employee = IDL.Record({
  'id' : EmployeeId,
  'status' : EmployeeStatus,
  'employeeCode' : IDL.Text,
  'iban' : IDL.Text,
  'createdAt' : Timestamp,
  'joiningDate' : Timestamp,
  'fullName' : IDL.Text,
  'nationality' : IDL.Text,
  'visaNumber' : IDL.Text,
  'bankName' : IDL.Text,
  'contractEndDate' : IDL.Opt(Timestamp),
  'emiratesId' : IDL.Text,
  'updatedAt' : Timestamp,
  'jobTitle' : IDL.Text,
  'passportNumber' : IDL.Text,
  'department' : IDL.Text,
  'contractStartDate' : Timestamp,
  'basicSalary' : IDL.Nat,
  'workLocation' : WorkLocation,
  'companyId' : CompanyId,
});
export const ApiError = IDL.Variant({
  'forbidden' : IDL.Text,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Text,
  'limitExceeded' : IDL.Text,
  'unauthorized' : IDL.Text,
});
export const Result_8 = IDL.Variant({ 'ok' : Employee, 'err' : ApiError });
export const VisaRecordType = IDL.Variant({
  'Contract' : IDL.Null,
  'Insurance' : IDL.Null,
  'Passport' : IDL.Null,
  'Visa' : IDL.Null,
  'LabourCard' : IDL.Null,
  'MedicalCard' : IDL.Null,
});
export const VisaRecordInput = IDL.Record({
  'expiryDate' : Timestamp,
  'recordType' : VisaRecordType,
  'employeeId' : EmployeeId,
  'notes' : IDL.Text,
});
export const VisaRecordId = IDL.Nat;
export const VisaRecord = IDL.Record({
  'id' : VisaRecordId,
  'expiryDate' : Timestamp,
  'createdAt' : Timestamp,
  'recordType' : VisaRecordType,
  'updatedAt' : Timestamp,
  'employeeId' : EmployeeId,
  'notes' : IDL.Text,
  'companyId' : CompanyId,
});
export const Result_5 = IDL.Variant({ 'ok' : VisaRecord, 'err' : ApiError });
export const PayrollRunId = IDL.Nat;
export const PayrollStatus = IDL.Variant({
  'HRApproved' : IDL.Null,
  'Paid' : IDL.Null,
  'AccountantReviewed' : IDL.Null,
  'Draft' : IDL.Null,
  'OwnerApproved' : IDL.Null,
  'Exported' : IDL.Null,
});
export const UserId = IDL.Nat;
export const PayrollRun = IDL.Record({
  'id' : PayrollRunId,
  'status' : PayrollStatus,
  'totalNetSalary' : IDL.Nat,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'hrApprovedAt' : IDL.Opt(Timestamp),
  'hrApprovedBy' : IDL.Opt(UserId),
  'payPeriodYear' : IDL.Nat,
  'accountantReviewedAt' : IDL.Opt(Timestamp),
  'accountantReviewedBy' : IDL.Opt(UserId),
  'exportedAt' : IDL.Opt(Timestamp),
  'notes' : IDL.Text,
  'ownerApprovedAt' : IDL.Opt(Timestamp),
  'ownerApprovedBy' : IDL.Opt(UserId),
  'payPeriodMonth' : IDL.Nat,
  'employeeIds' : IDL.Vec(EmployeeId),
  'companyId' : CompanyId,
});
export const Result_26 = IDL.Variant({ 'ok' : PayrollRun, 'err' : ApiError });
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmployeeImportRow = IDL.Record({
  'employeeCode' : IDL.Text,
  'fullName' : IDL.Text,
  'nationality' : IDL.Text,
  'jobTitle' : IDL.Text,
  'department' : IDL.Text,
  'basicSalary' : IDL.Nat,
  'workLocation' : IDL.Text,
});
export const ImportError = IDL.Record({ 'row' : IDL.Nat, 'reason' : IDL.Text });
export const ImportResult = IDL.Record({
  'imported' : IDL.Nat,
  'errors' : IDL.Vec(ImportError),
});
export const Result_33 = IDL.Variant({ 'ok' : ImportResult, 'err' : ApiError });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GeoLocation = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const CheckInInput = IDL.Record({
  'employeeId' : EmployeeId,
  'selfieBlob' : IDL.Opt(ExternalBlob),
  'consentGiven' : IDL.Bool,
  'checkInLocation' : IDL.Opt(GeoLocation),
});
export const AttendanceLogId = IDL.Nat;
export const AttendanceLog = IDL.Record({
  'id' : AttendanceLogId,
  'createdAt' : Timestamp,
  'checkInTime' : Timestamp,
  'employeeId' : EmployeeId,
  'selfieBlob' : IDL.Opt(ExternalBlob),
  'consentGiven' : IDL.Bool,
  'checkInLocation' : IDL.Opt(GeoLocation),
  'checkOutTime' : IDL.Opt(Timestamp),
  'checkOutLocation' : IDL.Opt(GeoLocation),
  'workHours' : IDL.Opt(IDL.Float64),
  'companyId' : CompanyId,
});
export const Result_32 = IDL.Variant({
  'ok' : AttendanceLog,
  'err' : ApiError,
});
export const CheckOutInput = IDL.Record({
  'logId' : AttendanceLogId,
  'checkOutLocation' : IDL.Opt(GeoLocation),
});
export const CreateNotificationEntry = IDL.Record({
  'notificationType' : IDL.Variant({
    'Salary' : IDL.Null,
    'VisaAlert' : IDL.Null,
    'PayrollApproval' : IDL.Null,
  }),
  'employeeId' : IDL.Opt(EmployeeId),
  'message' : IDL.Text,
});
export const NotificationLog = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'Failed' : IDL.Null,
    'Sent' : IDL.Null,
    'Pending' : IDL.Null,
  }),
  'notificationType' : IDL.Variant({
    'Salary' : IDL.Null,
    'VisaAlert' : IDL.Null,
    'PayrollApproval' : IDL.Null,
  }),
  'createdAt' : Timestamp,
  'employeeId' : IDL.Opt(EmployeeId),
  'message' : IDL.Text,
  'companyId' : CompanyId,
});
export const Result_31 = IDL.Variant({
  'ok' : NotificationLog,
  'err' : ApiError,
});
export const PayrollRunInput = IDL.Record({
  'payPeriodYear' : IDL.Nat,
  'notes' : IDL.Text,
  'payPeriodMonth' : IDL.Nat,
  'employeeIds' : IDL.Vec(EmployeeId),
});
export const UserStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'Suspended' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'Employee' : IDL.Null,
  'BranchManager' : IDL.Null,
  'SuperAdmin' : IDL.Null,
  'HRManager' : IDL.Null,
  'CompanyOwner' : IDL.Null,
  'Accountant' : IDL.Null,
});
export const User = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'principal' : IDL.Principal,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'lastLogin' : IDL.Opt(Timestamp),
  'companyId' : CompanyId,
});
export const Result_6 = IDL.Variant({ 'ok' : User, 'err' : ApiError });
export const DocumentId = IDL.Nat;
export const Result_10 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : ApiError });
export const WpsCountryFormat = IDL.Variant({
  'OmanMOL' : IDL.Null,
  'SaudiTemplate' : IDL.Null,
  'UAESIF' : IDL.Null,
  'QatarTemplate' : IDL.Null,
});
export const WpsExportInput = IDL.Record({
  'payrollRunId' : PayrollRunId,
  'countryFormat' : WpsCountryFormat,
});
export const WpsExportId = IDL.Nat;
export const WpsExportStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Generated' : IDL.Null,
  'Submitted' : IDL.Null,
});
export const WpsExport = IDL.Record({
  'id' : WpsExportId,
  'status' : WpsExportStatus,
  'employeeCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'fileName' : IDL.Text,
  'exportedBy' : UserId,
  'payrollRunId' : PayrollRunId,
  'countryFormat' : WpsCountryFormat,
  'companyId' : CompanyId,
});
export const Result_30 = IDL.Variant({
  'ok' : IDL.Record({ 'fileContent' : IDL.Text, 'export' : WpsExport }),
  'err' : ApiError,
});
export const Result_29 = IDL.Variant({
  'ok' : IDL.Opt(AttendanceLog),
  'err' : ApiError,
});
export const Result_28 = IDL.Variant({
  'ok' : IDL.Record({
    'totalEmployees' : IDL.Nat,
    'expiredVisaCount' : IDL.Nat,
    'unreadAlertCount' : IDL.Nat,
    'complianceScore' : IDL.Nat,
    'pendingPayrollCount' : IDL.Nat,
    'expiringDocumentCount' : IDL.Nat,
  }),
  'err' : ApiError,
});
export const RiskFactor = IDL.Record({
  'employeeCount' : IDL.Nat,
  'description' : IDL.Text,
  'severity' : IDL.Text,
  'factorType' : IDL.Variant({
    'PayrollDelay' : IDL.Null,
    'MissingDocument' : IDL.Null,
    'VisaExpiry' : IDL.Null,
    'WpsError' : IDL.Null,
  }),
  'estimatedFine' : IDL.Nat,
});
export const ComplianceRiskScore = IDL.Record({
  'riskFactors' : IDL.Vec(RiskFactor),
  'score' : IDL.Nat,
  'currency' : IDL.Text,
  'riskLevel' : IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  }),
  'penaltyExposure' : IDL.Nat,
});
export const Result_27 = IDL.Variant({
  'ok' : ComplianceRiskScore,
  'err' : ApiError,
});
export const DocumentType = IDL.Variant({
  'ID' : IDL.Null,
  'Contract' : IDL.Null,
  'Insurance' : IDL.Null,
  'PassportCopy' : IDL.Null,
  'Visa' : IDL.Null,
  'BankDocuments' : IDL.Null,
  'Medical' : IDL.Null,
});
export const EmployeeDocument = IDL.Record({
  'id' : DocumentId,
  'documentType' : DocumentType,
  'expiryDate' : IDL.Opt(Timestamp),
  'blob' : ExternalBlob,
  'createdAt' : Timestamp,
  'mimeType' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'employeeId' : EmployeeId,
  'uploadedBy' : UserId,
  'companyId' : CompanyId,
});
export const Result_2 = IDL.Variant({
  'ok' : EmployeeDocument,
  'err' : ApiError,
});
export const Result_13 = IDL.Variant({
  'ok' : IDL.Vec(VisaRecord),
  'err' : ApiError,
});
export const SubscriptionTier = IDL.Variant({
  'Starter' : IDL.Null,
  'Enterprise' : IDL.Null,
  'Growth' : IDL.Null,
  'Business' : IDL.Null,
});
export const Company = IDL.Record({
  'id' : CompanyId,
  'trialEndDate' : IDL.Opt(Timestamp),
  'country' : IDL.Text,
  'alertThresholdDays' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'subscriptionTier' : SubscriptionTier,
  'registrationNumber' : IDL.Text,
  'vatNumber' : IDL.Text,
  'address' : IDL.Text,
  'billingEmail' : IDL.Text,
  'phone' : IDL.Text,
});
export const Result_9 = IDL.Variant({ 'ok' : Company, 'err' : ApiError });
export const OnboardingProgress = IDL.Record({
  'completedAt' : IDL.Opt(Timestamp),
  'currentStep' : IDL.Nat,
  'stepsCompleted' : IDL.Vec(IDL.Bool),
  'companyId' : CompanyId,
});
export const Result_7 = IDL.Variant({
  'ok' : OnboardingProgress,
  'err' : ApiError,
});
export const PenaltyBreakdown = IDL.Record({
  'count' : IDL.Nat,
  'category' : IDL.Text,
  'amount' : IDL.Nat,
});
export const PenaltyExposure = IDL.Record({
  'total' : IDL.Nat,
  'breakdown' : IDL.Vec(PenaltyBreakdown),
  'currency' : IDL.Text,
});
export const Result_25 = IDL.Variant({
  'ok' : PenaltyExposure,
  'err' : ApiError,
});
export const ROIMetrics = IDL.Record({
  'payrollTotalAmount' : IDL.Nat,
  'timeSavedHours' : IDL.Float64,
  'complianceScoreImprovement' : IDL.Float64,
  'payrollProcessedCount' : IDL.Nat,
  'currency' : IDL.Text,
  'estimatedPenaltiesAvoided' : IDL.Nat,
});
export const Result_24 = IDL.Variant({ 'ok' : ROIMetrics, 'err' : ApiError });
export const SubscriptionId = IDL.Nat;
export const SubscriptionStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Expired' : IDL.Null,
});
export const Subscription = IDL.Record({
  'id' : SubscriptionId,
  'paidStartDate' : IDL.Opt(Timestamp),
  'status' : SubscriptionStatus,
  'trialEndDate' : IDL.Opt(Timestamp),
  'isTrialActive' : IDL.Bool,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
  'employeeLimit' : IDL.Nat,
  'trialStartDate' : IDL.Opt(Timestamp),
  'renewalDate' : IDL.Opt(Timestamp),
  'companyId' : CompanyId,
});
export const Result_3 = IDL.Variant({ 'ok' : Subscription, 'err' : ApiError });
export const WhatsAppSettings = IDL.Record({
  'payrollApprovalEnabled' : IDL.Bool,
  'employeeId' : EmployeeId,
  'salaryEnabled' : IDL.Bool,
  'phoneNumber' : IDL.Text,
  'visaAlertEnabled' : IDL.Bool,
});
export const Result_23 = IDL.Variant({
  'ok' : WhatsAppSettings,
  'err' : ApiError,
});
export const UserInput = IDL.Record({
  'role' : UserRole,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
});
export const AlertId = IDL.Nat;
export const AlertType = IDL.Variant({
  'DocumentExpiring' : IDL.Null,
  'PayrollPending' : IDL.Null,
  'VisaExpiring' : IDL.Null,
  'ComplianceRisk' : IDL.Null,
});
export const AlertSeverity = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const Alert = IDL.Record({
  'id' : AlertId,
  'alertType' : AlertType,
  'resourceId' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'employeeId' : IDL.Opt(EmployeeId),
  'message' : IDL.Text,
  'severity' : AlertSeverity,
  'readAt' : IDL.Opt(Timestamp),
  'readBy' : IDL.Opt(UserId),
  'companyId' : CompanyId,
});
export const Result_15 = IDL.Variant({
  'ok' : IDL.Vec(Alert),
  'err' : ApiError,
});
export const Result_22 = IDL.Variant({
  'ok' : IDL.Vec(AttendanceLog),
  'err' : ApiError,
});
export const Result_20 = IDL.Variant({
  'ok' : IDL.Vec(EmployeeDocument),
  'err' : ApiError,
});
export const AuditLogId = IDL.Nat;
export const AuditStatus = IDL.Variant({
  'Success' : IDL.Null,
  'Failure' : IDL.Null,
});
export const AuditActionType = IDL.Variant({
  'DocumentDeleted' : IDL.Null,
  'WPSExported' : IDL.Null,
  'DocumentDownloaded' : IDL.Null,
  'DocumentUploaded' : IDL.Null,
  'EmployeeAdded' : IDL.Null,
  'SalaryChanged' : IDL.Null,
  'AlertThresholdChanged' : IDL.Null,
  'EmployeeDeleted' : IDL.Null,
  'UserLogin' : IDL.Null,
  'RoleChanged' : IDL.Null,
  'CompanyProfileUpdated' : IDL.Null,
  'PayrollApproved' : IDL.Null,
});
export const AuditLog = IDL.Record({
  'id' : AuditLogId,
  'status' : AuditStatus,
  'oldValue' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'newValue' : IDL.Opt(IDL.Text),
  'actionType' : AuditActionType,
  'affectedResourceId' : IDL.Text,
  'affectedResourceName' : IDL.Text,
  'affectedResourceType' : IDL.Text,
  'companyId' : CompanyId,
});
export const Result_21 = IDL.Variant({
  'ok' : IDL.Vec(AuditLog),
  'err' : ApiError,
});
export const Result_19 = IDL.Variant({
  'ok' : IDL.Vec(Employee),
  'err' : ApiError,
});
export const Result_18 = IDL.Variant({
  'ok' : IDL.Vec(NotificationLog),
  'err' : ApiError,
});
export const PayrollItemId = IDL.Nat;
export const PayrollItem = IDL.Record({
  'id' : PayrollItemId,
  'createdAt' : Timestamp,
  'overtime' : IDL.Nat,
  'deductions' : IDL.Nat,
  'netSalary' : IDL.Nat,
  'payrollRunId' : PayrollRunId,
  'updatedAt' : Timestamp,
  'transportAllowance' : IDL.Nat,
  'employeeId' : EmployeeId,
  'leaveDeduction' : IDL.Nat,
  'basicSalary' : IDL.Nat,
  'advanceSalary' : IDL.Nat,
  'housingAllowance' : IDL.Nat,
});
export const Result_17 = IDL.Variant({
  'ok' : IDL.Vec(PayrollItem),
  'err' : ApiError,
});
export const Result_16 = IDL.Variant({
  'ok' : IDL.Vec(PayrollRun),
  'err' : ApiError,
});
export const Result_14 = IDL.Variant({
  'ok' : IDL.Vec(User),
  'err' : ApiError,
});
export const ExpiryStatus = IDL.Variant({
  'Valid' : IDL.Null,
  'ExpiringSoon' : IDL.Nat,
  'Expired' : IDL.Null,
});
export const Result_12 = IDL.Variant({
  'ok' : IDL.Vec(
    IDL.Record({ 'status' : ExpiryStatus, 'record' : VisaRecord })
  ),
  'err' : ApiError,
});
export const Result_11 = IDL.Variant({
  'ok' : IDL.Vec(WpsExport),
  'err' : ApiError,
});
export const CompanyInput = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'vatNumber' : IDL.Text,
  'address' : IDL.Text,
  'billingEmail' : IDL.Text,
  'phone' : IDL.Text,
});
export const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ApiError });
export const DocumentInput = IDL.Record({
  'documentType' : DocumentType,
  'expiryDate' : IDL.Opt(Timestamp),
  'blob' : ExternalBlob,
  'mimeType' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'employeeId' : EmployeeId,
});
export const PayrollItemInput = IDL.Record({
  'overtime' : IDL.Nat,
  'deductions' : IDL.Nat,
  'transportAllowance' : IDL.Nat,
  'employeeId' : EmployeeId,
  'leaveDeduction' : IDL.Nat,
  'basicSalary' : IDL.Nat,
  'advanceSalary' : IDL.Nat,
  'housingAllowance' : IDL.Nat,
});
export const Result_1 = IDL.Variant({ 'ok' : PayrollItem, 'err' : ApiError });
export const Result = IDL.Variant({
  'ok' : IDL.Vec(IDL.Text),
  'err' : ApiError,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addEmployee' : IDL.Func([EmployeeInput], [Result_8], []),
  'addVisaRecord' : IDL.Func([VisaRecordInput], [Result_5], []),
  'approvePayrollRun' : IDL.Func(
      [PayrollRunId, PayrollStatus],
      [Result_26],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'bulkImportEmployees' : IDL.Func(
      [IDL.Vec(EmployeeImportRow)],
      [Result_33],
      [],
    ),
  'checkIn' : IDL.Func([CheckInInput], [Result_32], []),
  'checkOut' : IDL.Func([CheckOutInput], [Result_32], []),
  'createNotificationLog' : IDL.Func(
      [CreateNotificationEntry],
      [Result_31],
      [],
    ),
  'createPayrollRun' : IDL.Func([PayrollRunInput], [Result_26], []),
  'deactivateUser' : IDL.Func([UserId], [Result_6], []),
  'deleteDocument' : IDL.Func([DocumentId], [Result_10], []),
  'generateWpsExport' : IDL.Func([WpsExportInput], [Result_30], []),
  'getActiveCheckIn' : IDL.Func([EmployeeId], [Result_29], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCompanyStats' : IDL.Func([], [Result_28], ['query']),
  'getComplianceRiskScore' : IDL.Func([], [Result_27], ['query']),
  'getDocument' : IDL.Func([DocumentId], [Result_2], ['query']),
  'getEmployee' : IDL.Func([EmployeeId], [Result_8], ['query']),
  'getExpiringRecords' : IDL.Func([IDL.Nat], [Result_13], ['query']),
  'getMyCompany' : IDL.Func([], [Result_9], ['query']),
  'getMyProfile' : IDL.Func([], [Result_6], ['query']),
  'getOnboardingProgress' : IDL.Func([], [Result_7], []),
  'getPayrollRun' : IDL.Func([PayrollRunId], [Result_26], ['query']),
  'getPenaltyExposure' : IDL.Func([], [Result_25], ['query']),
  'getROIMetrics' : IDL.Func([], [Result_24], []),
  'getSubscription' : IDL.Func([], [Result_3], ['query']),
  'getWhatsAppSettings' : IDL.Func([EmployeeId], [Result_23], []),
  'initSeedData' : IDL.Func([], [IDL.Bool], []),
  'inviteUser' : IDL.Func([UserInput], [Result_6], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSeedDataLoaded' : IDL.Func([], [IDL.Bool], ['query']),
  'listAlerts' : IDL.Func([], [Result_15], ['query']),
  'listAllAttendanceLogs' : IDL.Func([], [Result_22], ['query']),
  'listAllDocuments' : IDL.Func([], [Result_20], ['query']),
  'listAllVisaRecords' : IDL.Func([], [Result_13], ['query']),
  'listAttendanceByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [Result_22],
      ['query'],
    ),
  'listAttendanceLogs' : IDL.Func([EmployeeId], [Result_22], ['query']),
  'listAuditLogs' : IDL.Func([], [Result_21], ['query']),
  'listAuditLogsByAction' : IDL.Func([AuditActionType], [Result_21], ['query']),
  'listAuditLogsByDateRange' : IDL.Func(
      [Timestamp, Timestamp],
      [Result_21],
      ['query'],
    ),
  'listAuditLogsByUser' : IDL.Func([UserId], [Result_21], ['query']),
  'listDocuments' : IDL.Func([EmployeeId], [Result_20], ['query']),
  'listEmployees' : IDL.Func([], [Result_19], ['query']),
  'listNotificationLogs' : IDL.Func([IDL.Nat], [Result_18], []),
  'listPayrollItems' : IDL.Func([PayrollRunId], [Result_17], ['query']),
  'listPayrollRuns' : IDL.Func([], [Result_16], ['query']),
  'listUnreadAlerts' : IDL.Func([], [Result_15], ['query']),
  'listUsers' : IDL.Func([], [Result_14], ['query']),
  'listVisaRecords' : IDL.Func([EmployeeId], [Result_13], ['query']),
  'listVisaRecordsWithStatus' : IDL.Func([], [Result_12], ['query']),
  'listWpsExports' : IDL.Func([], [Result_11], ['query']),
  'logDocumentDownload' : IDL.Func([DocumentId], [Result_10], []),
  'markAlertRead' : IDL.Func([AlertId], [Result_10], []),
  'markAllAlertsRead' : IDL.Func([], [Result_10], []),
  'recordMyLogin' : IDL.Func([], [Result_6], []),
  'registerCompany' : IDL.Func([CompanyInput], [Result_9], []),
  'registerUser' : IDL.Func([CompanyId, UserInput], [Result_6], []),
  'removeEmployee' : IDL.Func([EmployeeId], [Result_10], []),
  'removeVisaRecord' : IDL.Func([VisaRecordId], [Result_10], []),
  'updateAlertThresholds' : IDL.Func([IDL.Vec(IDL.Nat)], [Result_9], []),
  'updateCompanyProfile' : IDL.Func([CompanyInput], [Result_9], []),
  'updateEmployee' : IDL.Func([EmployeeId, EmployeeInput], [Result_8], []),
  'updateOnboardingProgress' : IDL.Func([IDL.Nat], [Result_7], []),
  'updateUserRole' : IDL.Func([UserId, UserRole], [Result_6], []),
  'updateVisaRecord' : IDL.Func(
      [VisaRecordId, VisaRecordInput],
      [Result_5],
      [],
    ),
  'updateWhatsAppSettings' : IDL.Func([WhatsAppSettings], [Result_4], []),
  'upgradeSubscription' : IDL.Func([SubscriptionTier], [Result_3], []),
  'uploadDocument' : IDL.Func([DocumentInput], [Result_2], []),
  'upsertPayrollItem' : IDL.Func(
      [PayrollRunId, PayrollItemInput],
      [Result_1],
      [],
    ),
  'validateWpsData' : IDL.Func([PayrollRunId], [Result], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Int;
  const WorkLocation = IDL.Variant({
    'UAE' : IDL.Null,
    'Saudi' : IDL.Null,
    'Oman' : IDL.Null,
    'Kuwait' : IDL.Null,
    'Bahrain' : IDL.Null,
    'Qatar' : IDL.Null,
  });
  const EmployeeInput = IDL.Record({
    'employeeCode' : IDL.Text,
    'iban' : IDL.Text,
    'joiningDate' : Timestamp,
    'fullName' : IDL.Text,
    'nationality' : IDL.Text,
    'visaNumber' : IDL.Text,
    'bankName' : IDL.Text,
    'contractEndDate' : IDL.Opt(Timestamp),
    'emiratesId' : IDL.Text,
    'jobTitle' : IDL.Text,
    'passportNumber' : IDL.Text,
    'department' : IDL.Text,
    'contractStartDate' : Timestamp,
    'basicSalary' : IDL.Nat,
    'workLocation' : WorkLocation,
  });
  const EmployeeId = IDL.Nat;
  const EmployeeStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Separated' : IDL.Null,
    'OnLeave' : IDL.Null,
  });
  const CompanyId = IDL.Nat;
  const Employee = IDL.Record({
    'id' : EmployeeId,
    'status' : EmployeeStatus,
    'employeeCode' : IDL.Text,
    'iban' : IDL.Text,
    'createdAt' : Timestamp,
    'joiningDate' : Timestamp,
    'fullName' : IDL.Text,
    'nationality' : IDL.Text,
    'visaNumber' : IDL.Text,
    'bankName' : IDL.Text,
    'contractEndDate' : IDL.Opt(Timestamp),
    'emiratesId' : IDL.Text,
    'updatedAt' : Timestamp,
    'jobTitle' : IDL.Text,
    'passportNumber' : IDL.Text,
    'department' : IDL.Text,
    'contractStartDate' : Timestamp,
    'basicSalary' : IDL.Nat,
    'workLocation' : WorkLocation,
    'companyId' : CompanyId,
  });
  const ApiError = IDL.Variant({
    'forbidden' : IDL.Text,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Text,
    'limitExceeded' : IDL.Text,
    'unauthorized' : IDL.Text,
  });
  const Result_8 = IDL.Variant({ 'ok' : Employee, 'err' : ApiError });
  const VisaRecordType = IDL.Variant({
    'Contract' : IDL.Null,
    'Insurance' : IDL.Null,
    'Passport' : IDL.Null,
    'Visa' : IDL.Null,
    'LabourCard' : IDL.Null,
    'MedicalCard' : IDL.Null,
  });
  const VisaRecordInput = IDL.Record({
    'expiryDate' : Timestamp,
    'recordType' : VisaRecordType,
    'employeeId' : EmployeeId,
    'notes' : IDL.Text,
  });
  const VisaRecordId = IDL.Nat;
  const VisaRecord = IDL.Record({
    'id' : VisaRecordId,
    'expiryDate' : Timestamp,
    'createdAt' : Timestamp,
    'recordType' : VisaRecordType,
    'updatedAt' : Timestamp,
    'employeeId' : EmployeeId,
    'notes' : IDL.Text,
    'companyId' : CompanyId,
  });
  const Result_5 = IDL.Variant({ 'ok' : VisaRecord, 'err' : ApiError });
  const PayrollRunId = IDL.Nat;
  const PayrollStatus = IDL.Variant({
    'HRApproved' : IDL.Null,
    'Paid' : IDL.Null,
    'AccountantReviewed' : IDL.Null,
    'Draft' : IDL.Null,
    'OwnerApproved' : IDL.Null,
    'Exported' : IDL.Null,
  });
  const UserId = IDL.Nat;
  const PayrollRun = IDL.Record({
    'id' : PayrollRunId,
    'status' : PayrollStatus,
    'totalNetSalary' : IDL.Nat,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'hrApprovedAt' : IDL.Opt(Timestamp),
    'hrApprovedBy' : IDL.Opt(UserId),
    'payPeriodYear' : IDL.Nat,
    'accountantReviewedAt' : IDL.Opt(Timestamp),
    'accountantReviewedBy' : IDL.Opt(UserId),
    'exportedAt' : IDL.Opt(Timestamp),
    'notes' : IDL.Text,
    'ownerApprovedAt' : IDL.Opt(Timestamp),
    'ownerApprovedBy' : IDL.Opt(UserId),
    'payPeriodMonth' : IDL.Nat,
    'employeeIds' : IDL.Vec(EmployeeId),
    'companyId' : CompanyId,
  });
  const Result_26 = IDL.Variant({ 'ok' : PayrollRun, 'err' : ApiError });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmployeeImportRow = IDL.Record({
    'employeeCode' : IDL.Text,
    'fullName' : IDL.Text,
    'nationality' : IDL.Text,
    'jobTitle' : IDL.Text,
    'department' : IDL.Text,
    'basicSalary' : IDL.Nat,
    'workLocation' : IDL.Text,
  });
  const ImportError = IDL.Record({ 'row' : IDL.Nat, 'reason' : IDL.Text });
  const ImportResult = IDL.Record({
    'imported' : IDL.Nat,
    'errors' : IDL.Vec(ImportError),
  });
  const Result_33 = IDL.Variant({ 'ok' : ImportResult, 'err' : ApiError });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GeoLocation = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const CheckInInput = IDL.Record({
    'employeeId' : EmployeeId,
    'selfieBlob' : IDL.Opt(ExternalBlob),
    'consentGiven' : IDL.Bool,
    'checkInLocation' : IDL.Opt(GeoLocation),
  });
  const AttendanceLogId = IDL.Nat;
  const AttendanceLog = IDL.Record({
    'id' : AttendanceLogId,
    'createdAt' : Timestamp,
    'checkInTime' : Timestamp,
    'employeeId' : EmployeeId,
    'selfieBlob' : IDL.Opt(ExternalBlob),
    'consentGiven' : IDL.Bool,
    'checkInLocation' : IDL.Opt(GeoLocation),
    'checkOutTime' : IDL.Opt(Timestamp),
    'checkOutLocation' : IDL.Opt(GeoLocation),
    'workHours' : IDL.Opt(IDL.Float64),
    'companyId' : CompanyId,
  });
  const Result_32 = IDL.Variant({ 'ok' : AttendanceLog, 'err' : ApiError });
  const CheckOutInput = IDL.Record({
    'logId' : AttendanceLogId,
    'checkOutLocation' : IDL.Opt(GeoLocation),
  });
  const CreateNotificationEntry = IDL.Record({
    'notificationType' : IDL.Variant({
      'Salary' : IDL.Null,
      'VisaAlert' : IDL.Null,
      'PayrollApproval' : IDL.Null,
    }),
    'employeeId' : IDL.Opt(EmployeeId),
    'message' : IDL.Text,
  });
  const NotificationLog = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'Failed' : IDL.Null,
      'Sent' : IDL.Null,
      'Pending' : IDL.Null,
    }),
    'notificationType' : IDL.Variant({
      'Salary' : IDL.Null,
      'VisaAlert' : IDL.Null,
      'PayrollApproval' : IDL.Null,
    }),
    'createdAt' : Timestamp,
    'employeeId' : IDL.Opt(EmployeeId),
    'message' : IDL.Text,
    'companyId' : CompanyId,
  });
  const Result_31 = IDL.Variant({ 'ok' : NotificationLog, 'err' : ApiError });
  const PayrollRunInput = IDL.Record({
    'payPeriodYear' : IDL.Nat,
    'notes' : IDL.Text,
    'payPeriodMonth' : IDL.Nat,
    'employeeIds' : IDL.Vec(EmployeeId),
  });
  const UserStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'Suspended' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'Employee' : IDL.Null,
    'BranchManager' : IDL.Null,
    'SuperAdmin' : IDL.Null,
    'HRManager' : IDL.Null,
    'CompanyOwner' : IDL.Null,
    'Accountant' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'principal' : IDL.Principal,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'lastLogin' : IDL.Opt(Timestamp),
    'companyId' : CompanyId,
  });
  const Result_6 = IDL.Variant({ 'ok' : User, 'err' : ApiError });
  const DocumentId = IDL.Nat;
  const Result_10 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : ApiError });
  const WpsCountryFormat = IDL.Variant({
    'OmanMOL' : IDL.Null,
    'SaudiTemplate' : IDL.Null,
    'UAESIF' : IDL.Null,
    'QatarTemplate' : IDL.Null,
  });
  const WpsExportInput = IDL.Record({
    'payrollRunId' : PayrollRunId,
    'countryFormat' : WpsCountryFormat,
  });
  const WpsExportId = IDL.Nat;
  const WpsExportStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Generated' : IDL.Null,
    'Submitted' : IDL.Null,
  });
  const WpsExport = IDL.Record({
    'id' : WpsExportId,
    'status' : WpsExportStatus,
    'employeeCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'fileName' : IDL.Text,
    'exportedBy' : UserId,
    'payrollRunId' : PayrollRunId,
    'countryFormat' : WpsCountryFormat,
    'companyId' : CompanyId,
  });
  const Result_30 = IDL.Variant({
    'ok' : IDL.Record({ 'fileContent' : IDL.Text, 'export' : WpsExport }),
    'err' : ApiError,
  });
  const Result_29 = IDL.Variant({
    'ok' : IDL.Opt(AttendanceLog),
    'err' : ApiError,
  });
  const Result_28 = IDL.Variant({
    'ok' : IDL.Record({
      'totalEmployees' : IDL.Nat,
      'expiredVisaCount' : IDL.Nat,
      'unreadAlertCount' : IDL.Nat,
      'complianceScore' : IDL.Nat,
      'pendingPayrollCount' : IDL.Nat,
      'expiringDocumentCount' : IDL.Nat,
    }),
    'err' : ApiError,
  });
  const RiskFactor = IDL.Record({
    'employeeCount' : IDL.Nat,
    'description' : IDL.Text,
    'severity' : IDL.Text,
    'factorType' : IDL.Variant({
      'PayrollDelay' : IDL.Null,
      'MissingDocument' : IDL.Null,
      'VisaExpiry' : IDL.Null,
      'WpsError' : IDL.Null,
    }),
    'estimatedFine' : IDL.Nat,
  });
  const ComplianceRiskScore = IDL.Record({
    'riskFactors' : IDL.Vec(RiskFactor),
    'score' : IDL.Nat,
    'currency' : IDL.Text,
    'riskLevel' : IDL.Variant({
      'Low' : IDL.Null,
      'High' : IDL.Null,
      'Medium' : IDL.Null,
      'Critical' : IDL.Null,
    }),
    'penaltyExposure' : IDL.Nat,
  });
  const Result_27 = IDL.Variant({
    'ok' : ComplianceRiskScore,
    'err' : ApiError,
  });
  const DocumentType = IDL.Variant({
    'ID' : IDL.Null,
    'Contract' : IDL.Null,
    'Insurance' : IDL.Null,
    'PassportCopy' : IDL.Null,
    'Visa' : IDL.Null,
    'BankDocuments' : IDL.Null,
    'Medical' : IDL.Null,
  });
  const EmployeeDocument = IDL.Record({
    'id' : DocumentId,
    'documentType' : DocumentType,
    'expiryDate' : IDL.Opt(Timestamp),
    'blob' : ExternalBlob,
    'createdAt' : Timestamp,
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'employeeId' : EmployeeId,
    'uploadedBy' : UserId,
    'companyId' : CompanyId,
  });
  const Result_2 = IDL.Variant({ 'ok' : EmployeeDocument, 'err' : ApiError });
  const Result_13 = IDL.Variant({
    'ok' : IDL.Vec(VisaRecord),
    'err' : ApiError,
  });
  const SubscriptionTier = IDL.Variant({
    'Starter' : IDL.Null,
    'Enterprise' : IDL.Null,
    'Growth' : IDL.Null,
    'Business' : IDL.Null,
  });
  const Company = IDL.Record({
    'id' : CompanyId,
    'trialEndDate' : IDL.Opt(Timestamp),
    'country' : IDL.Text,
    'alertThresholdDays' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'subscriptionTier' : SubscriptionTier,
    'registrationNumber' : IDL.Text,
    'vatNumber' : IDL.Text,
    'address' : IDL.Text,
    'billingEmail' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Result_9 = IDL.Variant({ 'ok' : Company, 'err' : ApiError });
  const OnboardingProgress = IDL.Record({
    'completedAt' : IDL.Opt(Timestamp),
    'currentStep' : IDL.Nat,
    'stepsCompleted' : IDL.Vec(IDL.Bool),
    'companyId' : CompanyId,
  });
  const Result_7 = IDL.Variant({ 'ok' : OnboardingProgress, 'err' : ApiError });
  const PenaltyBreakdown = IDL.Record({
    'count' : IDL.Nat,
    'category' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const PenaltyExposure = IDL.Record({
    'total' : IDL.Nat,
    'breakdown' : IDL.Vec(PenaltyBreakdown),
    'currency' : IDL.Text,
  });
  const Result_25 = IDL.Variant({ 'ok' : PenaltyExposure, 'err' : ApiError });
  const ROIMetrics = IDL.Record({
    'payrollTotalAmount' : IDL.Nat,
    'timeSavedHours' : IDL.Float64,
    'complianceScoreImprovement' : IDL.Float64,
    'payrollProcessedCount' : IDL.Nat,
    'currency' : IDL.Text,
    'estimatedPenaltiesAvoided' : IDL.Nat,
  });
  const Result_24 = IDL.Variant({ 'ok' : ROIMetrics, 'err' : ApiError });
  const SubscriptionId = IDL.Nat;
  const SubscriptionStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'id' : SubscriptionId,
    'paidStartDate' : IDL.Opt(Timestamp),
    'status' : SubscriptionStatus,
    'trialEndDate' : IDL.Opt(Timestamp),
    'isTrialActive' : IDL.Bool,
    'createdAt' : Timestamp,
    'tier' : SubscriptionTier,
    'employeeLimit' : IDL.Nat,
    'trialStartDate' : IDL.Opt(Timestamp),
    'renewalDate' : IDL.Opt(Timestamp),
    'companyId' : CompanyId,
  });
  const Result_3 = IDL.Variant({ 'ok' : Subscription, 'err' : ApiError });
  const WhatsAppSettings = IDL.Record({
    'payrollApprovalEnabled' : IDL.Bool,
    'employeeId' : EmployeeId,
    'salaryEnabled' : IDL.Bool,
    'phoneNumber' : IDL.Text,
    'visaAlertEnabled' : IDL.Bool,
  });
  const Result_23 = IDL.Variant({ 'ok' : WhatsAppSettings, 'err' : ApiError });
  const UserInput = IDL.Record({
    'role' : UserRole,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
  });
  const AlertId = IDL.Nat;
  const AlertType = IDL.Variant({
    'DocumentExpiring' : IDL.Null,
    'PayrollPending' : IDL.Null,
    'VisaExpiring' : IDL.Null,
    'ComplianceRisk' : IDL.Null,
  });
  const AlertSeverity = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const Alert = IDL.Record({
    'id' : AlertId,
    'alertType' : AlertType,
    'resourceId' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'employeeId' : IDL.Opt(EmployeeId),
    'message' : IDL.Text,
    'severity' : AlertSeverity,
    'readAt' : IDL.Opt(Timestamp),
    'readBy' : IDL.Opt(UserId),
    'companyId' : CompanyId,
  });
  const Result_15 = IDL.Variant({ 'ok' : IDL.Vec(Alert), 'err' : ApiError });
  const Result_22 = IDL.Variant({
    'ok' : IDL.Vec(AttendanceLog),
    'err' : ApiError,
  });
  const Result_20 = IDL.Variant({
    'ok' : IDL.Vec(EmployeeDocument),
    'err' : ApiError,
  });
  const AuditLogId = IDL.Nat;
  const AuditStatus = IDL.Variant({
    'Success' : IDL.Null,
    'Failure' : IDL.Null,
  });
  const AuditActionType = IDL.Variant({
    'DocumentDeleted' : IDL.Null,
    'WPSExported' : IDL.Null,
    'DocumentDownloaded' : IDL.Null,
    'DocumentUploaded' : IDL.Null,
    'EmployeeAdded' : IDL.Null,
    'SalaryChanged' : IDL.Null,
    'AlertThresholdChanged' : IDL.Null,
    'EmployeeDeleted' : IDL.Null,
    'UserLogin' : IDL.Null,
    'RoleChanged' : IDL.Null,
    'CompanyProfileUpdated' : IDL.Null,
    'PayrollApproved' : IDL.Null,
  });
  const AuditLog = IDL.Record({
    'id' : AuditLogId,
    'status' : AuditStatus,
    'oldValue' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'newValue' : IDL.Opt(IDL.Text),
    'actionType' : AuditActionType,
    'affectedResourceId' : IDL.Text,
    'affectedResourceName' : IDL.Text,
    'affectedResourceType' : IDL.Text,
    'companyId' : CompanyId,
  });
  const Result_21 = IDL.Variant({ 'ok' : IDL.Vec(AuditLog), 'err' : ApiError });
  const Result_19 = IDL.Variant({ 'ok' : IDL.Vec(Employee), 'err' : ApiError });
  const Result_18 = IDL.Variant({
    'ok' : IDL.Vec(NotificationLog),
    'err' : ApiError,
  });
  const PayrollItemId = IDL.Nat;
  const PayrollItem = IDL.Record({
    'id' : PayrollItemId,
    'createdAt' : Timestamp,
    'overtime' : IDL.Nat,
    'deductions' : IDL.Nat,
    'netSalary' : IDL.Nat,
    'payrollRunId' : PayrollRunId,
    'updatedAt' : Timestamp,
    'transportAllowance' : IDL.Nat,
    'employeeId' : EmployeeId,
    'leaveDeduction' : IDL.Nat,
    'basicSalary' : IDL.Nat,
    'advanceSalary' : IDL.Nat,
    'housingAllowance' : IDL.Nat,
  });
  const Result_17 = IDL.Variant({
    'ok' : IDL.Vec(PayrollItem),
    'err' : ApiError,
  });
  const Result_16 = IDL.Variant({
    'ok' : IDL.Vec(PayrollRun),
    'err' : ApiError,
  });
  const Result_14 = IDL.Variant({ 'ok' : IDL.Vec(User), 'err' : ApiError });
  const ExpiryStatus = IDL.Variant({
    'Valid' : IDL.Null,
    'ExpiringSoon' : IDL.Nat,
    'Expired' : IDL.Null,
  });
  const Result_12 = IDL.Variant({
    'ok' : IDL.Vec(
      IDL.Record({ 'status' : ExpiryStatus, 'record' : VisaRecord })
    ),
    'err' : ApiError,
  });
  const Result_11 = IDL.Variant({
    'ok' : IDL.Vec(WpsExport),
    'err' : ApiError,
  });
  const CompanyInput = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'vatNumber' : IDL.Text,
    'address' : IDL.Text,
    'billingEmail' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ApiError });
  const DocumentInput = IDL.Record({
    'documentType' : DocumentType,
    'expiryDate' : IDL.Opt(Timestamp),
    'blob' : ExternalBlob,
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'employeeId' : EmployeeId,
  });
  const PayrollItemInput = IDL.Record({
    'overtime' : IDL.Nat,
    'deductions' : IDL.Nat,
    'transportAllowance' : IDL.Nat,
    'employeeId' : EmployeeId,
    'leaveDeduction' : IDL.Nat,
    'basicSalary' : IDL.Nat,
    'advanceSalary' : IDL.Nat,
    'housingAllowance' : IDL.Nat,
  });
  const Result_1 = IDL.Variant({ 'ok' : PayrollItem, 'err' : ApiError });
  const Result = IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : ApiError });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addEmployee' : IDL.Func([EmployeeInput], [Result_8], []),
    'addVisaRecord' : IDL.Func([VisaRecordInput], [Result_5], []),
    'approvePayrollRun' : IDL.Func(
        [PayrollRunId, PayrollStatus],
        [Result_26],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'bulkImportEmployees' : IDL.Func(
        [IDL.Vec(EmployeeImportRow)],
        [Result_33],
        [],
      ),
    'checkIn' : IDL.Func([CheckInInput], [Result_32], []),
    'checkOut' : IDL.Func([CheckOutInput], [Result_32], []),
    'createNotificationLog' : IDL.Func(
        [CreateNotificationEntry],
        [Result_31],
        [],
      ),
    'createPayrollRun' : IDL.Func([PayrollRunInput], [Result_26], []),
    'deactivateUser' : IDL.Func([UserId], [Result_6], []),
    'deleteDocument' : IDL.Func([DocumentId], [Result_10], []),
    'generateWpsExport' : IDL.Func([WpsExportInput], [Result_30], []),
    'getActiveCheckIn' : IDL.Func([EmployeeId], [Result_29], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCompanyStats' : IDL.Func([], [Result_28], ['query']),
    'getComplianceRiskScore' : IDL.Func([], [Result_27], ['query']),
    'getDocument' : IDL.Func([DocumentId], [Result_2], ['query']),
    'getEmployee' : IDL.Func([EmployeeId], [Result_8], ['query']),
    'getExpiringRecords' : IDL.Func([IDL.Nat], [Result_13], ['query']),
    'getMyCompany' : IDL.Func([], [Result_9], ['query']),
    'getMyProfile' : IDL.Func([], [Result_6], ['query']),
    'getOnboardingProgress' : IDL.Func([], [Result_7], []),
    'getPayrollRun' : IDL.Func([PayrollRunId], [Result_26], ['query']),
    'getPenaltyExposure' : IDL.Func([], [Result_25], ['query']),
    'getROIMetrics' : IDL.Func([], [Result_24], []),
    'getSubscription' : IDL.Func([], [Result_3], ['query']),
    'getWhatsAppSettings' : IDL.Func([EmployeeId], [Result_23], []),
    'initSeedData' : IDL.Func([], [IDL.Bool], []),
    'inviteUser' : IDL.Func([UserInput], [Result_6], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSeedDataLoaded' : IDL.Func([], [IDL.Bool], ['query']),
    'listAlerts' : IDL.Func([], [Result_15], ['query']),
    'listAllAttendanceLogs' : IDL.Func([], [Result_22], ['query']),
    'listAllDocuments' : IDL.Func([], [Result_20], ['query']),
    'listAllVisaRecords' : IDL.Func([], [Result_13], ['query']),
    'listAttendanceByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [Result_22],
        ['query'],
      ),
    'listAttendanceLogs' : IDL.Func([EmployeeId], [Result_22], ['query']),
    'listAuditLogs' : IDL.Func([], [Result_21], ['query']),
    'listAuditLogsByAction' : IDL.Func(
        [AuditActionType],
        [Result_21],
        ['query'],
      ),
    'listAuditLogsByDateRange' : IDL.Func(
        [Timestamp, Timestamp],
        [Result_21],
        ['query'],
      ),
    'listAuditLogsByUser' : IDL.Func([UserId], [Result_21], ['query']),
    'listDocuments' : IDL.Func([EmployeeId], [Result_20], ['query']),
    'listEmployees' : IDL.Func([], [Result_19], ['query']),
    'listNotificationLogs' : IDL.Func([IDL.Nat], [Result_18], []),
    'listPayrollItems' : IDL.Func([PayrollRunId], [Result_17], ['query']),
    'listPayrollRuns' : IDL.Func([], [Result_16], ['query']),
    'listUnreadAlerts' : IDL.Func([], [Result_15], ['query']),
    'listUsers' : IDL.Func([], [Result_14], ['query']),
    'listVisaRecords' : IDL.Func([EmployeeId], [Result_13], ['query']),
    'listVisaRecordsWithStatus' : IDL.Func([], [Result_12], ['query']),
    'listWpsExports' : IDL.Func([], [Result_11], ['query']),
    'logDocumentDownload' : IDL.Func([DocumentId], [Result_10], []),
    'markAlertRead' : IDL.Func([AlertId], [Result_10], []),
    'markAllAlertsRead' : IDL.Func([], [Result_10], []),
    'recordMyLogin' : IDL.Func([], [Result_6], []),
    'registerCompany' : IDL.Func([CompanyInput], [Result_9], []),
    'registerUser' : IDL.Func([CompanyId, UserInput], [Result_6], []),
    'removeEmployee' : IDL.Func([EmployeeId], [Result_10], []),
    'removeVisaRecord' : IDL.Func([VisaRecordId], [Result_10], []),
    'updateAlertThresholds' : IDL.Func([IDL.Vec(IDL.Nat)], [Result_9], []),
    'updateCompanyProfile' : IDL.Func([CompanyInput], [Result_9], []),
    'updateEmployee' : IDL.Func([EmployeeId, EmployeeInput], [Result_8], []),
    'updateOnboardingProgress' : IDL.Func([IDL.Nat], [Result_7], []),
    'updateUserRole' : IDL.Func([UserId, UserRole], [Result_6], []),
    'updateVisaRecord' : IDL.Func(
        [VisaRecordId, VisaRecordInput],
        [Result_5],
        [],
      ),
    'updateWhatsAppSettings' : IDL.Func([WhatsAppSettings], [Result_4], []),
    'upgradeSubscription' : IDL.Func([SubscriptionTier], [Result_3], []),
    'uploadDocument' : IDL.Func([DocumentInput], [Result_2], []),
    'upsertPayrollItem' : IDL.Func(
        [PayrollRunId, PayrollItemInput],
        [Result_1],
        [],
      ),
    'validateWpsData' : IDL.Func([PayrollRunId], [Result], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };